// AUTO-GENERATED by scripts/build-bis.mjs — do not edit by hand.
import type { BisList } from "@/lib/bis";
import list0 from "@/data/bis/rogue-subtlety-pvp.json";
import list1 from "@/data/bis/druid-restoration-pvp.json";
import list2 from "@/data/bis/rogue-combat-pvp.json";
import list3 from "@/data/bis/mage-frost-pvp.json";
import list4 from "@/data/bis/priest-discipline-pvp.json";
import list5 from "@/data/bis/warrior-arms-pvp.json";
import list6 from "@/data/bis/mage-arcane-pvp.json";
import list7 from "@/data/bis/warlock-demonology-pvp.json";
import list8 from "@/data/bis/shaman-restoration-pvp.json";
import list9 from "@/data/bis/priest-holy-pvp.json";
import list10 from "@/data/bis/priest-shadow-pvp.json";
import list11 from "@/data/bis/paladin-retribution-pvp.json";
import list12 from "@/data/bis/druid-balance-pvp.json";
import list13 from "@/data/bis/hunter-survival-pvp.json";
import list14 from "@/data/bis/warlock-destruction-pvp.json";
import list15 from "@/data/bis/paladin-holy-pvp.json";
import list16 from "@/data/bis/warlock-affliction-pvp.json";
import list17 from "@/data/bis/shaman-enhancement-pvp.json";
import list18 from "@/data/bis/hunter-marksmanship-pvp.json";
import list19 from "@/data/bis/druid-feral-cat-pvp.json";
import list20 from "@/data/bis/hunter-beast-mastery-pvp.json";
import list21 from "@/data/bis/warrior-fury-pvp.json";
import list22 from "@/data/bis/warrior-protection-pvp.json";
import list23 from "@/data/bis/shaman-elemental-pvp.json";

export const BIS_REGISTRY: Record<string, BisList> = {
 "rogue/subtlety/pvp": list0 as BisList,
 "druid/restoration/pvp": list1 as BisList,
 "rogue/combat/pvp": list2 as BisList,
 "mage/frost/pvp": list3 as BisList,
 "priest/discipline/pvp": list4 as BisList,
 "warrior/arms/pvp": list5 as BisList,
 "mage/arcane/pvp": list6 as BisList,
 "warlock/demonology/pvp": list7 as BisList,
 "shaman/restoration/pvp": list8 as BisList,
 "priest/holy/pvp": list9 as BisList,
 "priest/shadow/pvp": list10 as BisList,
 "paladin/retribution/pvp": list11 as BisList,
 "druid/balance/pvp": list12 as BisList,
 "hunter/survival/pvp": list13 as BisList,
 "warlock/destruction/pvp": list14 as BisList,
 "paladin/holy/pvp": list15 as BisList,
 "warlock/affliction/pvp": list16 as BisList,
 "shaman/enhancement/pvp": list17 as BisList,
 "hunter/marksmanship/pvp": list18 as BisList,
 "druid/feral-cat/pvp": list19 as BisList,
 "hunter/beast-mastery/pvp": list20 as BisList,
 "warrior/fury/pvp": list21 as BisList,
 "warrior/protection/pvp": list22 as BisList,
 "shaman/elemental/pvp": list23 as BisList,
};
