// BiS dataset access. Lists are generated by scripts/build-bis.mjs from
// a weekly arena-leaderboard snapshot (public armory data, aggregated
// via ironforge.pro) merged with our hand-written editorial layer in
// scripts/bis-editorial.mjs. Item icons/names come from data/items.json,
// resolved via the Wowhead tooltip API (github.com/iamcal/Wowhead-API).
//
// Re-run `node scripts/build-bis.mjs` to refresh the snapshot; never
// hand-edit the generated JSON.

import { BIS_REGISTRY } from "@/data/bis/index";
import { PHASES, type Phase } from "@/lib/classes";

export type BisSlotName =
  | "Head" | "Neck" | "Shoulders" | "Back" | "Chest" | "Wrist" | "Hands"
  | "Waist" | "Legs" | "Feet" | "Ring" | "Ring1" | "Ring2" | "Trinket"
  | "Trinket1" | "Trinket2" | "MainHand" | "OffHand" | "Ranged";

export interface BisItemRef {
  itemId: number;
  name?: string;
  usagePct?: number;
  pveFlexNote?: string;
}

export interface BisSlot {
  slot: BisSlotName;
  bis: BisItemRef;
  alternatives: BisItemRef[];
}

export interface BisFaqItem {
  question: string;
  answer: string;
}

export interface BisList {
  class: string;
  spec: string;
  content: "pvp" | "pve";
  phase?: number; // pve only: 1..5
  season?: number; // pvp only: 1..4 (2 = live snapshot)
  seasonPage?: boolean; // true = derived per-season page (not the live snapshot)
  ratingRange?: [number, number]; // pvp only, live snapshot
  sampleSize?: number;
  updatedAt: string; // ISO date
  blurb: string; // hand-written per-spec editorial (anti-thin-content)
  statPriorityRationale: string;
  statPriority: string[];
  slots: BisSlot[];
  gems: { itemId: number; name?: string; note: string }[];
  enchants: {
    slot: string;
    text: string;
    note: string;
    /** Enchant/formula name, e.g. "Glyph of Ferocity". */
    name?: string;
    /** zamimg icon name for the enchant formula. */
    icon?: string;
    /** Where it comes from — vendor/rep/drop and its zone. */
    source?: string;
  }[];
  faq: BisFaqItem[];
}

// TBC arena seasons. Season 2 is the live ladder snapshot; 1/3/4 are
// derived per-season pages generated by scripts/build-pvp-seasons.mjs.
export const PVP_SEASONS = [1, 2, 3, 4] as const;
export type PvpSeason = (typeof PVP_SEASONS)[number];
export const LIVE_SEASON: PvpSeason = 2;

export const SEASON_NAMES: Record<PvpSeason, string> = {
  1: "Gladiator",
  2: "Merciless Gladiator",
  3: "Vengeful Gladiator",
  4: "Brutal Gladiator",
};

/** The live-snapshot PvP list (Season 2). */
export function getPvpBis(classSlug: string, specSlug: string): BisList | null {
  return BIS_REGISTRY[`${classSlug}/${specSlug}/pvp`] ?? null;
}

/** A specific PvP season: the live snapshot for 2, a derived page otherwise. */
export function getPvpSeasonBis(
  classSlug: string,
  specSlug: string,
  season: PvpSeason,
): BisList | null {
  if (season === LIVE_SEASON) return getPvpBis(classSlug, specSlug);
  return BIS_REGISTRY[`${classSlug}/${specSlug}/pvp/s${season}`] ?? null;
}

/** Which PvP seasons have a page for this spec (always includes live). */
export function availablePvpSeasons(
  classSlug: string,
  specSlug: string,
): PvpSeason[] {
  return PVP_SEASONS.filter((s) =>
    Boolean(getPvpSeasonBis(classSlug, specSlug, s)),
  );
}

export function getPveBis(
  classSlug: string,
  specSlug: string,
  phase: Phase,
): BisList | null {
  return BIS_REGISTRY[`${classSlug}/${specSlug}/pve/${phase}`] ?? null;
}

/** Which PvE phases have a filled list for this spec (for the phase tabs). */
export function availablePhases(classSlug: string, specSlug: string): Phase[] {
  return PHASES.filter((p) => Boolean(getPveBis(classSlug, specSlug, p)));
}

/** All filled lists — drives the sitemap (unfilled specs stay out). */
export function filledBisRoutes(): {
  classSlug: string;
  specSlug: string;
  content: "pvp" | "pve";
  phase?: number;
  season?: number;
  seasonPage?: boolean;
  updatedAt: string;
}[] {
  return Object.values(BIS_REGISTRY).map((list) => ({
    classSlug: list.class,
    specSlug: list.spec,
    content: list.content,
    phase: list.phase,
    season: list.season,
    seasonPage: list.seasonPage,
    updatedAt: list.updatedAt,
  }));
}

export function wowheadItemUrl(itemId: number): string {
  return `https://www.wowhead.com/tbc/item=${itemId}`;
}
