// BiS dataset access. Lists are generated by scripts/build-bis.mjs from
// a weekly arena-leaderboard snapshot (public armory data, aggregated
// via ironforge.pro) merged with our hand-written editorial layer in
// scripts/bis-editorial.mjs. Item icons/names come from data/items.json,
// resolved via the Wowhead tooltip API (github.com/iamcal/Wowhead-API).
//
// Re-run `node scripts/build-bis.mjs` to refresh the snapshot; never
// hand-edit the generated JSON.

import { BIS_REGISTRY } from "@/data/bis/index";
import type { Phase } from "@/lib/classes";

export type BisSlotName =
  | "Head" | "Neck" | "Shoulders" | "Back" | "Chest" | "Wrist" | "Hands"
  | "Waist" | "Legs" | "Feet" | "Ring" | "Trinket" | "MainHand" | "OffHand"
  | "Ranged";

export interface BisItemRef {
  itemId: number;
  name?: string;
  usagePct?: number;
  pveFlexNote?: string;
}

export interface BisSlot {
  slot: BisSlotName;
  bis: BisItemRef;
  alternatives: BisItemRef[];
}

export interface BisFaqItem {
  question: string;
  answer: string;
}

export interface BisList {
  class: string;
  spec: string;
  content: "pvp" | "pve";
  phase?: number; // pve only: 1..5
  season?: number; // pvp only
  ratingRange?: [number, number]; // pvp only
  sampleSize?: number;
  updatedAt: string; // ISO date
  blurb: string; // hand-written per-spec editorial (anti-thin-content)
  statPriorityRationale: string;
  statPriority: string[];
  slots: BisSlot[];
  gems: { itemId: number; name?: string; note: string }[];
  enchants: { slot: string; text: string; note: string }[];
  faq: BisFaqItem[];
}

export function getPvpBis(classSlug: string, specSlug: string): BisList | null {
  return BIS_REGISTRY[`${classSlug}/${specSlug}/pvp`] ?? null;
}

export function getPveBis(
  classSlug: string,
  specSlug: string,
  phase: Phase,
): BisList | null {
  return BIS_REGISTRY[`${classSlug}/${specSlug}/pve/${phase}`] ?? null;
}

/** All filled lists — drives the sitemap (unfilled specs stay out). */
export function filledBisRoutes(): {
  classSlug: string;
  specSlug: string;
  content: "pvp" | "pve";
  phase?: number;
  updatedAt: string;
}[] {
  return Object.values(BIS_REGISTRY).map((list) => ({
    classSlug: list.class,
    specSlug: list.spec,
    content: list.content,
    phase: list.phase,
    updatedAt: list.updatedAt,
  }));
}

export function wowheadItemUrl(itemId: number): string {
  return `https://www.wowhead.com/tbc/item=${itemId}`;
}
