// Talent data access. JSON is generated by scripts/build-talents.mjs
// from wowsims/tbc (structure) + Wowhead (names/icons/descriptions) —
// never hand-edit the JSON; re-run the script instead.

import druid from "@/data/talents/druid.json";
import hunter from "@/data/talents/hunter.json";
import mage from "@/data/talents/mage.json";
import paladin from "@/data/talents/paladin.json";
import priest from "@/data/talents/priest.json";
import rogue from "@/data/talents/rogue.json";
import shaman from "@/data/talents/shaman.json";
import warlock from "@/data/talents/warlock.json";
import warrior from "@/data/talents/warrior.json";

export interface Talent {
  id: string;
  name: string;
  icon: string; // Wowhead icon name for the zamimg CDN
  row: number; // 0-based tier
  col: number; // 0-3 column
  maxRank: number;
  spellIds: number[]; // one per rank — used for Wowhead hover tooltips
  description: string; // rank-1 text (offline fallback)
  requiresPoints: number; // points needed in tree to unlock (row * 5)
  requires?: { talentId: string; ranks: number };
}

export interface TalentTree {
  class: string;
  treeName: string;
  background?: string;
  talents: Talent[];
}

export interface ClassTalents {
  class: string;
  trees: TalentTree[];
}

const TALENTS: Record<string, ClassTalents> = {
  druid: druid as ClassTalents,
  hunter: hunter as ClassTalents,
  mage: mage as ClassTalents,
  paladin: paladin as ClassTalents,
  priest: priest as ClassTalents,
  rogue: rogue as ClassTalents,
  shaman: shaman as ClassTalents,
  warlock: warlock as ClassTalents,
  warrior: warrior as ClassTalents,
};

export const TOTAL_POINTS = 61; // level 70: 61 talent points

export function getTalents(classSlug: string): ClassTalents | undefined {
  return TALENTS[classSlug];
}

// ——— Build strings ———
// Per tree: one digit per talent in dataset order (row-major, matching
// Wowhead's ordering), trailing zeros trimmed; trees joined by "-".
// Example: "05005301-0-505030105".

export type BuildState = number[][]; // ranks per talent, per tree

export function emptyBuild(cls: ClassTalents): BuildState {
  return cls.trees.map((t) => t.talents.map(() => 0));
}

export function encodeBuild(build: BuildState): string {
  return build
    .map((tree) => tree.join("").replace(/0+$/, ""))
    .join("-")
    .replace(/-+$/, "");
}

export function decodeBuild(cls: ClassTalents, encoded: string): BuildState {
  const parts = encoded.split("-");
  return cls.trees.map((tree, ti) => {
    const digits = parts[ti] ?? "";
    return tree.talents.map((talent, i) => {
      const d = Number(digits[i] ?? 0);
      if (!Number.isInteger(d) || d < 0) return 0;
      return Math.min(d, talent.maxRank);
    });
  });
}

export function treePoints(build: BuildState, treeIndex: number): number {
  return build[treeIndex].reduce((s, r) => s + r, 0);
}

export function totalPoints(build: BuildState): number {
  return build.reduce((s, tree) => s + tree.reduce((a, r) => a + r, 0), 0);
}

/** e.g. "40/0/21" */
export function buildSummary(build: BuildState): string {
  return build.map((tree) => tree.reduce((a, r) => a + r, 0)).join("/");
}

/** Wowhead TBC talent-calc link for cross-checking a build. */
export function wowheadCalcUrl(classSlug: string, build: BuildState): string {
  const str = build.map((tree) => tree.join("").replace(/0+$/, "")).join("-");
  return `https://www.wowhead.com/tbc/talent-calc/${classSlug}/${str}`;
}
