// Item acquisition sources, keyed by Wowhead item id. Generated by
// scripts/build-item-sources.mjs from Wowhead's &xml `sourcemore` data
// (authoritative — it corrects hand-seeded mistakes). Last scope: pillars
// (137 items resolved). Pages render the source on slot-expand.
//
// Re-run: node scripts/build-item-sources.mjs all

export interface ItemSourceEntry {
  type: "raid" | "dungeon" | "vendor" | "crafted" | "pvp" | "world" | "quest";
  location: string;
  boss?: string;
  dropRate?: string;
  currency?: string;
  profession?: string;
}

export interface ItemSource {
  itemId: number;
  sources: ItemSourceEntry[];
}

const SOURCES: Record<number, ItemSourceEntry[]> = {
  23763: [{"type":"crafted","location":"Crafted"}],
  24128: [{"type":"crafted","location":"Crafted"}],
  25644: [{"type":"quest","location":"The Ultimate Bloodsport"}],
  25645: [{"type":"quest","location":"The Ultimate Bloodsport"}],
  25832: [{"type":"pvp","location":"Honor vendor (Area 52, Netherstorm)","currency":"Honor + Battleground marks"}],
  25834: [{"type":"pvp","location":"Honor vendor (Area 52, Netherstorm)","currency":"Honor + Battleground marks"}],
  27886: [{"type":"dungeon","location":"Shadow Labyrinth","boss":"Ambassador Hellmaw"}],
  27917: [{"type":"dungeon","location":"Mana-Tombs","boss":"Darkweaver Syth"}],
  28190: [{"type":"world","location":"Aeonus"}],
  28234: [{"type":"vendor","location":"Master Sergeant Biggins (Stormwind City)"}],
  28235: [{"type":"vendor","location":"Master Sergeant Biggins (Stormwind City)"}],
  28236: [{"type":"vendor","location":"Master Sergeant Biggins (Stormwind City)"}],
  28238: [{"type":"vendor","location":"Master Sergeant Biggins (Stormwind City)"}],
  28239: [{"type":"vendor","location":"Brave Stonehide (Orgrimmar)"}],
  28240: [{"type":"vendor","location":"Brave Stonehide (Orgrimmar)"}],
  28241: [{"type":"vendor","location":"Brave Stonehide (Orgrimmar)"}],
  28242: [{"type":"vendor","location":"Brave Stonehide (Orgrimmar)"}],
  28296: [{"type":"dungeon","location":"The Botanica","boss":"Commander Sarannis"}],
  28370: [{"type":"dungeon","location":"The Botanica","boss":"Warp Splinter"}],
  28441: [{"type":"crafted","location":"Crafted"}],
  28442: [{"type":"crafted","location":"Crafted"}],
  28503: [{"type":"raid","location":"Karazhan"}],
  28509: [{"type":"raid","location":"Karazhan"}],
  28512: [{"type":"raid","location":"Karazhan","boss":"Maiden of Virtue"}],
  28520: [{"type":"raid","location":"Karazhan","boss":"Maiden of Virtue"}],
  28523: [{"type":"raid","location":"Karazhan","boss":"Maiden of Virtue"}],
  28525: [{"type":"raid","location":"Karazhan","boss":"Moroes"}],
  28545: [{"type":"raid","location":"Karazhan","boss":"Moroes"}],
  28553: [{"type":"vendor","location":"Terokkar Forest"}],
  28555: [{"type":"vendor","location":"Terokkar Forest"}],
  28570: [{"type":"raid","location":"Karazhan","boss":"Moroes"}],
  28582: [{"type":"raid","location":"Karazhan","boss":"The Big Bad Wolf"}],
  28588: [{"type":"raid","location":"Karazhan","boss":"The Crone"}],
  28591: [{"type":"raid","location":"Karazhan"}],
  28594: [{"type":"raid","location":"Karazhan"}],
  28603: [{"type":"raid","location":"Karazhan","boss":"Nightbane"}],
  28609: [{"type":"raid","location":"Karazhan","boss":"Nightbane"}],
  28649: [{"type":"raid","location":"Karazhan","boss":"The Curator"}],
  28663: [{"type":"raid","location":"Karazhan","boss":"Shade of Aran"}],
  28672: [{"type":"raid","location":"Karazhan","boss":"Shade of Aran"}],
  28673: [{"type":"raid","location":"Karazhan","boss":"Shade of Aran"}],
  28727: [{"type":"raid","location":"Karazhan","boss":"Shade of Aran"}],
  28731: [{"type":"raid","location":"Karazhan","boss":"Netherspite"}],
  28741: [{"type":"raid","location":"Karazhan","boss":"Netherspite"}],
  28750: [{"type":"raid","location":"Karazhan","boss":"Dust Covered Chest"}],
  28751: [{"type":"raid","location":"Karazhan","boss":"Dust Covered Chest"}],
  28754: [{"type":"raid","location":"Karazhan","boss":"Dust Covered Chest"}],
  28757: [{"type":"raid","location":"Karazhan","boss":"Prince Malchezaar"}],
  28763: [{"type":"raid","location":"Karazhan","boss":"Prince Malchezaar"}],
  28765: [{"type":"raid","location":"Karazhan","boss":"Prince Malchezaar"}],
  28766: [{"type":"raid","location":"Karazhan","boss":"Prince Malchezaar"}],
  28770: [{"type":"raid","location":"Karazhan","boss":"Prince Malchezaar"}],
  28771: [{"type":"raid","location":"Karazhan","boss":"Prince Malchezaar"}],
  28777: [{"type":"raid","location":"Magtheridon's Lair"}],
  28783: [{"type":"raid","location":"Magtheridon's Lair"}],
  28795: [{"type":"raid","location":"Gruul's Lair","boss":"High King Maulgar"}],
  28797: [{"type":"raid","location":"Gruul's Lair","boss":"High King Maulgar"}],
  28799: [{"type":"raid","location":"Gruul's Lair","boss":"High King Maulgar"}],
  28822: [{"type":"raid","location":"Gruul's Lair","boss":"Gruul the Dragonkiller"}],
  28830: [{"type":"raid","location":"Gruul's Lair","boss":"Gruul the Dragonkiller"}],
  29028: [{"type":"vendor","location":"Shattrath City"}],
  29049: [{"type":"vendor","location":"Shattrath City"}],
  29272: [{"type":"vendor","location":"G'eras (Shattrath City)"}],
  29274: [{"type":"vendor","location":"G'eras (Shattrath City)"}],
  29347: [{"type":"dungeon","location":"The Blood Furnace","boss":"Keli'dan the Breaker"}],
  29370: [{"type":"vendor","location":"G'eras (Shattrath City)"}],
  29374: [{"type":"vendor","location":"G'eras (Shattrath City)"}],
  29375: [{"type":"vendor","location":"G'eras (Shattrath City)"}],
  29376: [{"type":"vendor","location":"G'eras (Shattrath City)"}],
  29381: [{"type":"vendor","location":"G'eras (Shattrath City)"}],
  29382: [{"type":"vendor","location":"G'eras (Shattrath City)"}],
  29383: [{"type":"vendor","location":"G'eras (Shattrath City)"}],
  29458: [{"type":"raid","location":"Magtheridon's Lair"}],
  29923: [{"type":"raid","location":"Tempest Keep: The Eye","boss":"Al'ar"}],
  29966: [{"type":"raid","location":"Tempest Keep: The Eye","boss":"High Astromancer Solarian"}],
  29976: [{"type":"raid","location":"Tempest Keep: The Eye","boss":"High Astromancer Solarian"}],
  29981: [{"type":"raid","location":"Tempest Keep: The Eye","boss":"High Astromancer Solarian"}],
  29984: [{"type":"raid","location":"Tempest Keep: The Eye","boss":"Void Reaver"}],
  29989: [{"type":"raid","location":"Tempest Keep: The Eye","boss":"Kael'thas Sunstrider"}],
  29991: [{"type":"raid","location":"Tempest Keep: The Eye","boss":"Kael'thas Sunstrider"}],
  29992: [{"type":"raid","location":"Tempest Keep: The Eye","boss":"Kael'thas Sunstrider"}],
  29994: [{"type":"raid","location":"Tempest Keep: The Eye","boss":"Kael'thas Sunstrider"}],
  29996: [{"type":"raid","location":"Tempest Keep: The Eye","boss":"Kael'thas Sunstrider"}],
  29997: [{"type":"raid","location":"Tempest Keep: The Eye","boss":"Kael'thas Sunstrider"}],
  30008: [{"type":"raid","location":"Serpentshrine Cavern","boss":"Morogrim Tidewalker"}],
  30017: [{"type":"quest","location":"Kael'thas and the Verdant Sphere"}],
  30018: [{"type":"quest","location":"Kael'thas and the Verdant Sphere"}],
  30022: [{"type":"raid","location":"Serpentshrine Cavern"}],
  30025: [{"type":"raid","location":"Serpentshrine Cavern"}],
  30027: [{"type":"raid","location":"Serpentshrine Cavern"}],
  30030: [{"type":"raid","location":"Tempest Keep: The Eye"}],
  30032: [{"type":"crafted","location":"Crafted"}],
  30035: [{"type":"crafted","location":"Crafted"}],
  30036: [{"type":"crafted","location":"Crafted"}],
  30040: [{"type":"crafted","location":"Crafted"}],
  30044: [{"type":"crafted","location":"Crafted"}],
  30047: [{"type":"raid","location":"Serpentshrine Cavern"}],
  30052: [{"type":"raid","location":"Serpentshrine Cavern"}],
  30056: [{"type":"raid","location":"Serpentshrine Cavern"}],
  30062: [{"type":"raid","location":"Serpentshrine Cavern","boss":"The Lurker Below"}],
  30064: [{"type":"raid","location":"Serpentshrine Cavern","boss":"The Lurker Below"}],
  30066: [{"type":"raid","location":"Serpentshrine Cavern","boss":"The Lurker Below"}],
  30080: [{"type":"raid","location":"Serpentshrine Cavern","boss":"Morogrim Tidewalker"}],
  30081: [{"type":"raid","location":"Serpentshrine Cavern","boss":"Morogrim Tidewalker"}],
  30082: [{"type":"raid","location":"Serpentshrine Cavern","boss":"Morogrim Tidewalker"}],
  30092: [{"type":"raid","location":"Serpentshrine Cavern"}],
  30095: [{"type":"raid","location":"Serpentshrine Cavern"}],
  30098: [{"type":"raid","location":"Serpentshrine Cavern","boss":"Morogrim Tidewalker"}],
  30100: [{"type":"raid","location":"Serpentshrine Cavern","boss":"Fathom-Lord Karathress"}],
  30107: [{"type":"raid","location":"Serpentshrine Cavern","boss":"Lady Vashj"}],
  30108: [{"type":"raid","location":"Serpentshrine Cavern","boss":"Lady Vashj"}],
  30110: [{"type":"raid","location":"Serpentshrine Cavern","boss":"Lady Vashj"}],
  30112: [{"type":"raid","location":"Serpentshrine Cavern","boss":"Lady Vashj"}],
  30118: [{"type":"vendor","location":"Shattrath City"}],
  30120: [{"type":"vendor","location":"Shattrath City"}],
  30134: [{"type":"vendor","location":"Shattrath City"}],
  30135: [{"type":"vendor","location":"Shattrath City"}],
  30136: [{"type":"vendor","location":"Shattrath City"}],
  30137: [{"type":"vendor","location":"Shattrath City"}],
  30138: [{"type":"vendor","location":"Shattrath City"}],
  30145: [{"type":"raid","location":"Karazhan (Tier 4 token turn-in)","boss":"The Curator"}],
  30146: [{"type":"raid","location":"Karazhan / Gruul's Lair (Tier 4 token turn-in)","boss":"Prince Malchezaar / Gruul"}],
  30148: [{"type":"vendor","location":"Shattrath City"}],
  30149: [{"type":"raid","location":"Magtheridon's Lair (Tier 4 token turn-in)","boss":"Magtheridon"}],
  30152: [{"type":"vendor","location":"Shattrath City"}],
  30164: [{"type":"vendor","location":"Shattrath City"}],
  30166: [{"type":"vendor","location":"Shattrath City"}],
  30168: [{"type":"vendor","location":"Shattrath City"}],
  30219: [{"type":"vendor","location":"Shattrath City"}],
  30220: [{"type":"vendor","location":"Shattrath City"}],
  30343: [{"type":"vendor","location":"Brave Stonehide (Orgrimmar)"}],
  30344: [{"type":"vendor","location":"Brave Stonehide (Orgrimmar)"}],
  30345: [{"type":"vendor","location":"Brave Stonehide (Orgrimmar)"}],
  30346: [{"type":"vendor","location":"Brave Stonehide (Orgrimmar)"}],
  30348: [{"type":"vendor","location":"Master Sergeant Biggins (Stormwind City)"}],
  30349: [{"type":"vendor","location":"Master Sergeant Biggins (Stormwind City)"}],
  30350: [{"type":"vendor","location":"Master Sergeant Biggins (Stormwind City)"}],
  30351: [{"type":"vendor","location":"Master Sergeant Biggins (Stormwind City)"}],
  30450: [{"type":"dungeon","location":"The Botanica","boss":"Warp Splinter"}],
  30665: [{"type":"raid","location":"Serpentshrine Cavern","boss":"The Lurker Below"}],
  31998: [{"type":"pvp","location":"Arena / Honor vendor (Area 52, Netherstorm)","currency":"Honor + Battleground marks"}],
  31999: [{"type":"pvp","location":"Arena / Honor vendor (Area 52, Netherstorm)","currency":"Honor + Battleground marks"}],
  32000: [{"type":"pvp","location":"Arena vendor (Area 52, Netherstorm)","currency":"Arena points (rating required)"}],
  32001: [{"type":"pvp","location":"Arena vendor (Area 52, Netherstorm)","currency":"Arena points (rating required)"}],
  32002: [{"type":"pvp","location":"Arena / Honor vendor (Area 52, Netherstorm)","currency":"Honor + Battleground marks"}],
  32027: [{"type":"pvp","location":"Arena vendor (Area 52, Netherstorm)","currency":"Arena points (rating required)"}],
  32052: [{"type":"pvp","location":"Arena vendor (Area 52, Netherstorm)","currency":"Arena points (rating required)"}],
  32054: [{"type":"pvp","location":"Arena vendor (Area 52, Netherstorm)","currency":"Arena points (rating required)"}],
  32478: [{"type":"crafted","location":"Crafted"}],
  32494: [{"type":"crafted","location":"Crafted"}],
  32516: [{"type":"raid","location":"Serpentshrine Cavern"}],
};

const TYPE_LABEL: Record<ItemSourceEntry["type"], string> = {
  raid: "Raid",
  dungeon: "Dungeon",
  vendor: "Vendor",
  crafted: "Crafted",
  pvp: "PvP",
  world: "World Drop",
  quest: "Quest",
};

export function getItemSource(itemId: number): ItemSourceEntry[] | null {
  return SOURCES[itemId] ?? null;
}

/** One-line human string, e.g. "Raid — Karazhan (Prince Malchezaar)". */
export function formatItemSource(s: ItemSourceEntry): string {
  const parts = [TYPE_LABEL[s.type], "—", s.location];
  const extra = [s.boss, s.dropRate, s.currency, s.profession].filter(Boolean);
  let str = parts.join(" ");
  if (extra.length) str += ` (${extra.join(", ")})`;
  return str;
}
