// GENERATED by scripts/build-raid-routes.mjs — do not edit by hand.
//
// Maps the raid/boss names recorded in data/itemSources.ts to the routes
// this site publishes, so a BiS item's "how to get" line can link to the
// actual boss guide. Kept free of data/raids.ts imports because it is
// reached from a client component.

export interface RaidRoute {
  raidId: string;
  phase: number;
  /** Raid display name, for link text. */
  raid: string;
}

export interface BossRoute extends RaidRoute {
  bossId: string;
  /** Boss display name, for link text. */
  boss: string;
}

/** Normalised raid/location name → raid route. */
export const RAID_ROUTES: Record<string, RaidRoute> = {
  "blacktemple": { raidId: "black-temple", phase: 3, raid: "Black Temple" },
  "gruulslair": { raidId: "gruuls-lair", phase: 1, raid: "Gruul's Lair" },
  "hyjalsummit": { raidId: "mount-hyjal", phase: 3, raid: "Mount Hyjal" },
  "karazhan": { raidId: "karazhan", phase: 1, raid: "Karazhan" },
  "magtheridonslair": { raidId: "magtheridons-lair", phase: 1, raid: "Magtheridon's Lair" },
  "mounthyjal": { raidId: "mount-hyjal", phase: 3, raid: "Mount Hyjal" },
  "serpentshrinecavern": { raidId: "serpentshrine-cavern", phase: 2, raid: "Serpentshrine Cavern" },
  "sunwellplateau": { raidId: "sunwell-plateau", phase: 5, raid: "Sunwell Plateau" },
  "tempestkeep": { raidId: "tempest-keep", phase: 2, raid: "Tempest Keep: The Eye" },
  "tempestkeeptheeye": { raidId: "tempest-keep", phase: 2, raid: "Tempest Keep: The Eye" },
  "thebattleformounthyjal": { raidId: "mount-hyjal", phase: 3, raid: "Mount Hyjal" },
  "theeye": { raidId: "tempest-keep", phase: 2, raid: "Tempest Keep: The Eye" },
  "zulaman": { raidId: "zulaman", phase: 4, raid: "Zul'Aman" },
};

/** Normalised boss name → boss route. */
export const BOSS_ROUTES: Record<string, BossRoute> = {
  "akilzon": { raidId: "zulaman", phase: 4, raid: "Zul'Aman", bossId: "akilzon", boss: "Akil'zon" },
  "alar": { raidId: "tempest-keep", phase: 2, raid: "Tempest Keep: The Eye", bossId: "alar", boss: "Al'ar" },
  "anetheron": { raidId: "mount-hyjal", phase: 3, raid: "Mount Hyjal", bossId: "anetheron", boss: "Anetheron" },
  "archimonde": { raidId: "mount-hyjal", phase: 3, raid: "Mount Hyjal", bossId: "archimonde", boss: "Archimonde" },
  "attumenthehuntsman": { raidId: "karazhan", phase: 1, raid: "Karazhan", bossId: "attumen-the-huntsman", boss: "Attumen the Huntsman" },
  "azgalor": { raidId: "mount-hyjal", phase: 3, raid: "Mount Hyjal", bossId: "azgalor", boss: "Azgalor" },
  "brutallus": { raidId: "sunwell-plateau", phase: 5, raid: "Sunwell Plateau", bossId: "brutallus", boss: "Brutallus" },
  "eredartwins": { raidId: "sunwell-plateau", phase: 5, raid: "Sunwell Plateau", bossId: "eredar-twins", boss: "Eredar Twins" },
  "fathomlordkarathress": { raidId: "serpentshrine-cavern", phase: 2, raid: "Serpentshrine Cavern", bossId: "fathom-lord-karathress", boss: "Fathom-Lord Karathress" },
  "felmyst": { raidId: "sunwell-plateau", phase: 5, raid: "Sunwell Plateau", bossId: "felmyst", boss: "Felmyst" },
  "gruulthedragonkiller": { raidId: "gruuls-lair", phase: 1, raid: "Gruul's Lair", bossId: "gruul-the-dragonkiller", boss: "Gruul the Dragonkiller" },
  "gurtoggbloodboil": { raidId: "black-temple", phase: 3, raid: "Black Temple", bossId: "gurtogg-bloodboil", boss: "Gurtogg Bloodboil" },
  "halazzi": { raidId: "zulaman", phase: 4, raid: "Zul'Aman", bossId: "halazzi", boss: "Halazzi" },
  "hexlordmalacrass": { raidId: "zulaman", phase: 4, raid: "Zul'Aman", bossId: "hex-lord-malacrass", boss: "Hex Lord Malacrass" },
  "highastromancersolarian": { raidId: "tempest-keep", phase: 2, raid: "Tempest Keep: The Eye", bossId: "high-astromancer-solarian", boss: "High Astromancer Solarian" },
  "highkingmaulgar": { raidId: "gruuls-lair", phase: 1, raid: "Gruul's Lair", bossId: "high-king-maulgar", boss: "High King Maulgar" },
  "highwarlordnajentus": { raidId: "black-temple", phase: 3, raid: "Black Temple", bossId: "high-warlord-najentus", boss: "High Warlord Naj'entus" },
  "hydrosstheunstable": { raidId: "serpentshrine-cavern", phase: 2, raid: "Serpentshrine Cavern", bossId: "hydross-the-unstable", boss: "Hydross the Unstable" },
  "illidanstormrage": { raidId: "black-temple", phase: 3, raid: "Black Temple", bossId: "illidan-stormrage", boss: "Illidan Stormrage" },
  "illidaricouncil": { raidId: "black-temple", phase: 3, raid: "Black Temple", bossId: "illidari-council", boss: "Illidari Council" },
  "janalai": { raidId: "zulaman", phase: 4, raid: "Zul'Aman", bossId: "janalai", boss: "Jan'alai" },
  "kaelthassunstrider": { raidId: "tempest-keep", phase: 2, raid: "Tempest Keep: The Eye", bossId: "kaelthas-sunstrider", boss: "Kael'thas Sunstrider" },
  "kalecgos": { raidId: "sunwell-plateau", phase: 5, raid: "Sunwell Plateau", bossId: "kalecgos", boss: "Kalecgos" },
  "kazrogal": { raidId: "mount-hyjal", phase: 3, raid: "Mount Hyjal", bossId: "kazrogal", boss: "Kaz'rogal" },
  "kiljaeden": { raidId: "sunwell-plateau", phase: 5, raid: "Sunwell Plateau", bossId: "kiljaeden", boss: "Kil'jaeden" },
  "ladyvashj": { raidId: "serpentshrine-cavern", phase: 2, raid: "Serpentshrine Cavern", bossId: "lady-vashj", boss: "Lady Vashj" },
  "leotherastheblind": { raidId: "serpentshrine-cavern", phase: 2, raid: "Serpentshrine Cavern", bossId: "leotheras-the-blind", boss: "Leotheras the Blind" },
  "magtheridon": { raidId: "magtheridons-lair", phase: 1, raid: "Magtheridon's Lair", bossId: "magtheridon", boss: "Magtheridon" },
  "maidenofvirtue": { raidId: "karazhan", phase: 1, raid: "Karazhan", bossId: "maiden-of-virtue", boss: "Maiden of Virtue" },
  "moroes": { raidId: "karazhan", phase: 1, raid: "Karazhan", bossId: "moroes", boss: "Moroes" },
  "morogrimtidewalker": { raidId: "serpentshrine-cavern", phase: 2, raid: "Serpentshrine Cavern", bossId: "morogrim-tidewalker", boss: "Morogrim Tidewalker" },
  "mothershahraz": { raidId: "black-temple", phase: 3, raid: "Black Temple", bossId: "mother-shahraz", boss: "Mother Shahraz" },
  "muru": { raidId: "sunwell-plateau", phase: 5, raid: "Sunwell Plateau", bossId: "muru", boss: "M'uru" },
  "nalorakk": { raidId: "zulaman", phase: 4, raid: "Zul'Aman", bossId: "nalorakk", boss: "Nalorakk" },
  "netherspite": { raidId: "karazhan", phase: 1, raid: "Karazhan", bossId: "netherspite", boss: "Netherspite" },
  "operaevent": { raidId: "karazhan", phase: 1, raid: "Karazhan", bossId: "opera-event", boss: "Opera Event" },
  "princemalchezaar": { raidId: "karazhan", phase: 1, raid: "Karazhan", bossId: "prince-malchezaar", boss: "Prince Malchezaar" },
  "ragewinterchill": { raidId: "mount-hyjal", phase: 3, raid: "Mount Hyjal", bossId: "rage-winterchill", boss: "Rage Winterchill" },
  "reliquaryofsouls": { raidId: "black-temple", phase: 3, raid: "Black Temple", bossId: "reliquary-of-souls", boss: "Reliquary of Souls" },
  "shadeofakama": { raidId: "black-temple", phase: 3, raid: "Black Temple", bossId: "shade-of-akama", boss: "Shade of Akama" },
  "shadeofaran": { raidId: "karazhan", phase: 1, raid: "Karazhan", bossId: "shade-of-aran", boss: "Shade of Aran" },
  "supremus": { raidId: "black-temple", phase: 3, raid: "Black Temple", bossId: "supremus", boss: "Supremus" },
  "terestianillhoof": { raidId: "karazhan", phase: 1, raid: "Karazhan", bossId: "terestian-illhoof", boss: "Terestian Illhoof" },
  "terongorefiend": { raidId: "black-temple", phase: 3, raid: "Black Temple", bossId: "teron-gorefiend", boss: "Teron Gorefiend" },
  "thecurator": { raidId: "karazhan", phase: 1, raid: "Karazhan", bossId: "the-curator", boss: "The Curator" },
  "thelurkerbelow": { raidId: "serpentshrine-cavern", phase: 2, raid: "Serpentshrine Cavern", bossId: "the-lurker-below", boss: "The Lurker Below" },
  "voidreaver": { raidId: "tempest-keep", phase: 2, raid: "Tempest Keep: The Eye", bossId: "void-reaver", boss: "Void Reaver" },
  "zuljin": { raidId: "zulaman", phase: 4, raid: "Zul'Aman", bossId: "zuljin", boss: "Zul'jin" },
};
